config/routes.rb
Rails.application.routes.draw do
  root "welcome#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/pokedex", to: "users#index"
  delete "/logout", to: "sessions#destroy"

  resources :welcome, only: [:index]
  resources :pokemons, only: [:show]

  resources :users, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon
  attr_reader :name,
              :weight,
              :height,
              :type_1,
              :type_2,
              :image,
              :id

  def initialize(poke_data)
    @name = poke_data[:name] 
    @weight = poke_data[:weight] 
    @height = poke_data[:height]
    @type_1 = check_type_1_exists(poke_data)
    @type_2 = poke_data[:types][0][:type][:name]
    @image = poke_data[:sprites][:front_default]
    @id = poke_data[:id]
  end

  def self.find_pokemon(id)
   poke_data = poke_service.get_pokemon(id)
    Pokemon.new(poke_data)
  end

  def self.poke_service
    PokemonService.new
  end

  def check_type_1_exists(poke_data)
  #  poke_data[:types][1] && poke_data[:types][1][:type][:name]
    if !poke_data[:types][1].nil?
      poke_data[:types][1][:type][:name]
    else
      "Pokemon only has one type"
    end
  end

  def self.find_starters
    [1,4,7].each do |id|
      data = poke_service.get_pokemon(id)
      (@poke_array ||= []).push(Pokemon.new(data))
    end
    @poke_array
  end

  def self.find_species(id)
    url = poke_service.get_species(id)
    data = url[:evolution_chain][:url]
    find_evolutions(data)
  end



  def self.find_evolutions(url)
    @critters = []
    evolutions = poke_service.main_connect(url)
    first(evolutions)
    middle(evolutions)
    last(evolutions)
    species_array(@critters)
  end


  def self.species_array(critters)
    critters.each do |criter|
      data = poke_service.get_pokemon(criter)
      (@critters_array ||= []).push(Pokemon.new(data))
    end
    @critters_array
  end

  def self.first(evolutions)
    if !evolutions[:chain][:species].nil?
      @critters.push(evolutions[:chain][:species][:name])
    end
  end 

  def self.middle(evolutions)
    if !evolutions[:chain][:evolves_to][0].nil?
      @critters.push(evolutions[:chain][:evolves_to][0][:species][:name])
    end
  end

  def self.last(evolutions)
    if !evolutions[:chain][:evolves_to][0][:evolves_to][0].nil?
      @critters.push(evolutions[:chain][:evolves_to][0][:evolves_to][0][:species][:name])
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def show
    pokemon = params[:id]
    @species = Pokemon.find_species(pokemon)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "#{user.username} Has Successfully Logged In"
      redirect_to pokedex_path
    else
      flash[:error] = "Incorrect entry"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:danger] = "Logged Out"
    redirect_to root_path
  end

  private
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      redirect_to pokedex_path
      flash[:success] = "You're in the great game now'"
    else
      render :new
      flash[:danger] = "Something Went Wrong, Try Again."
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @pokemon = Pokemon.find_starters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeCritters</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if current_user %>
    <%= render partial: "shared/user_nav"%>
  <% else %>
    <%= render partial: "shared/guest_nav"%>
  <% end %>
  
  <body>
    <div style= 'text-align:center'>
      <% flash.each do |type, message| %>
        <%= content_tag :div, sanitize(message), class:"alert-#{type}"%>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pokemons/show.html.erb
<div class="container">
  <%@species.each do |pokemon|%>
    <%=image_tag(pokemon.image)%> </br>
    Name: <%=pokemon.name.capitalize%> </br>
    Weight: <%=pokemon.weight%>lbs </br>
    Height: <%=pokemon.height%>in </br>
    Type 1: <%=pokemon.type_1%> </br>
    Type 2: <%=pokemon.type_2%> </br>
  <% end %>
</div>

app/views/shared/_guest_nav.html.erb
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="/">PokeCritters</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/login">Login</a>
    </div>
  </div>
</nav>

app/views/shared/_user_nav.html.erb
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="/">PokeCritters</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/users"> Pokedex <span class="sr-only">(current)</span></a>
      <%= link_to "Logout", logout_path, method: "delete", class: "nav-item nav-link"%>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1><%=@user.username%>'s Pokedex</h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :username, placeholder: "Username"%>
  <%= f.text_field :first_name, placeholder: "First Name"%>
  <%= f.text_field :last_name, placeholder: "Last Name"%>
  <%= f.text_field :email, placeholder: "Email"%>
  <%= f.password_field :password, placeholder: "Password"%>
  <%= f.password_field :password_confirmation, placeholder: "Password Confirmation"%>
  <%= f.submit "Join Now"%>
<% end %>



  

app/views/welcome/show.html.erb
<div class="container">
  <h1 class="welcome-tag">PokeCritters</h1><br>
  <h2 class="welcome-subheading">Gotta Catch em All</h2>
</div>

<div class="container">
  <% @pokemon.each do |pokemon|%><br>
    <%=image_tag(pokemon.image)%><br>
   Name: <%=link_to pokemon.name.capitalize, pokemon_path(pokemon.id)%><br>
   Weight: <%=pokemon.weight%><br>
   Height: <%=pokemon.height%><br>
   Type 1: <%=pokemon.type_1%><br>
   Type 2: <%=pokemon.type_2%><br>

  <%end%>
</div>